### ISSUE TITLE
[Feature] UI: Improve layout of image viewer in image gallery

### ISSUE THREAD

**Issue by echo6ix** [boi123212321/porn-vault#365]
**Is your feature request related to a problem? Please describe.**
To improve the  use of space (larger image size, and better presentation of metadata, and other clickable icons) when viewing images from the image gallery in both desktop and mobile modes

**Describe the solution you'd like**
I've attached two concepts, desktop and mobile, which are taken from Dropbox's web app and Android app. I use both for an image gallery, image viewer, and for editing image metadata and properties. I find both desktop and mobile viewports are flawless at accomplishing these tasks without cluttering the UI and still keeping the image as a maximal focal point.

### desktop concept

This concept has two main sections: the left (containing the image), and the right (a pinnable/collapsible side bar with details, metadata, etc)

![desktop](https://user-images.githubusercontent.com/37937507/75844794-26ca4a80-5da5-11ea-88d0-5f037dee2e0c.png)
Important features include:
- The main image, displayed on the left contains minimal padding around all margins to maximize size of image
- The toolbar overlay on the bottom right contains: navigation carets, numerical position of image in index; full screen button; magnification buttons. The semi-transparent toolbar overlay on the image means the image can occupy more of the screen because the current left/right navigation buttons needn't occupy space on the left and right margins
- The right pinnable/collapsible sidebar contains two sections:
  - the left section which is collapsible and would replace the current "show details" section, including things like file properties, path, file size, image dimensions
  - the right section of vertically stacked icons are not collapsible. they remain right justified and contain all pertinent icons such as:
    - The "the collapse/pin" button, delete image button, bookmark button, favorite button, direct link button, and may contain other buttons that act as tabs such as a "show details" aka metadata button, and "file properties" button
    - Since icons are stacked vertically, there is much space for future growth of any other feature enhancements added
 - Collapsing the sidebar expands the image to occupy almost the entire view port

### mobile concept
Most people are going to be using their mobile mode to view navigate their images in full bleed mode. Therefore, the most important feature of this concept is that the image is presented in full bleed (no padding on the left and right margins). Left and right swipes navigation through the image gallery.

Per the screenshot below from the Dropbox app, the bottom and top areas can be used to display icons that access fav'ing, bookmarking, etc, and the ability to open a drawer to show the metadata aka "show details"

![mobile](https://user-images.githubusercontent.com/37937507/75846638-f1c0f680-5daa-11ea-9593-048f08654411.png)

**Comment by yoshnopa** [comment]
The Desktop view looks perfect wo me now, however to me in the mobile view there needs to be a way to go into landscape mode. This is basically working, however, the image size should be adjusted so that it fits on the screen without scrolling I think (meaning the image doesnt go from left to right side of the webpage if necessary).
