### ISSUE TITLE
[Feature] Allow parallax scrolling and transparent UI effects for hero image

### ISSUE THREAD

**Issue by Red5ive-UK** [boi123212321/porn-vault#416]
Hero image is great but the narrow aspect ratio makes finding images that fit very tough and making it bigger would take up too much of the UI space.

Possible solution could be to allow a parallax effect to the image and/or make parts of the UI transparent, such as the menu bar or actor description/meta area.

**Comment by LostRune** [comment]
+1, even if i find a picture with the proper resolution and aspect ratio the image gets cropped out.
The feature seems to work perfectly for 4:3 resolutions, but not for 16:9.

**Comment by boi123212321** [comment]
Continued here https://github.com/boi123212321/porn-vault/issues/807
