### ISSUE TITLE
[Feature] Global search

### ISSUE THREAD

**Issue by Ziatexataor** [boi123212321/porn-vault#439]
Custom data fields are unsearchable. Ex. if I added a custom data field to an actor or a scene I can't search to find actors or scenes with that custom data field.
The search query requires a complete word to find something. Ex. if I'm searching for "America" and I only typed "Americ" the search finds nothing,

A global search would be great, searching everywhere for a given text.

**Comment by boi123212321** [comment]
is planned ever since custom data is a thing, but needs a search engine overhaul
