### ISSUE TITLE
[Feature] Rework the search engine to find results faster

### ISSUE THREAD

**Issue by PDSmokes** [boi123212321/porn-vault#440]
**Is your feature request related to a problem? Please describe.**
When assigning a Studio to a video it can be rather weird. Sometimes it requires you to put in the entire name until it finds the right Studio.

**Describe the solution you'd like**
It would be nice to have a list from when you write the first letter. So if i write S then it shows all Studios starting with S, then when i add w it shows all starting with Sw and so on. Would make life a bit easier

**Comment by boi123212321** [comment]
Working as currently intended, but once I get to rewriting the search engine this will change.
Currently, items are indexed by _words_.

**Comment by boi123212321** [comment]
should kinda work as of 0.22 but i can't guarantee it will always find relevant stuff
