### ISSUE TITLE
[Feature] Images - quick button for avatar,thumb,alt. thumb, hero

### ISSUE THREAD

**Issue by Ch00nassid** [boi123212321/porn-vault#510]
**Is your feature request related to a problem? Please describe.**
Currently, there is only a "Quick change" button for the main thumbnail.  I just downloaded 200 picture sets of my favorite actor and am setting the Tumb, alt. thum and hero image.  I noticed that I did not like the compressed image when i added the pictures through the "change" menu.  
![image](https://user-images.githubusercontent.com/57732969/80932554-9a78db80-8d85-11ea-8de0-653982b54b41.png)

When I use the "**set as actor thumbnail**" i find the quality is much better.  
![image](https://user-images.githubusercontent.com/57732969/80932548-91880a00-8d85-11ea-9627-1daae44e1909.png)

I find that I am modifying the .DB files after i have used the "**Change**" options, to point to the main image to increase the quality.

IMPORTANT NOTE:  I do not change the hero image that is configured using the "change menu" -- I leave that picture in-tact.

**Describe the solution you'd like**

I would like to have 4 "set" buttons created for:

- avatar
- thumbnail
- alt. thumbnail
- hero

Note:  the Hero and Avatar "snippet" system should still be triggered when selecting an image to set. (Or have a choice not to use the snippet system?  Personally, i think that's silly)

**Additional context**
This system would make it so that i don't have to modify the (actors).DB files and restart to see the higher quality images i would like to have set.

**Comment by Ch00nassid** [comment]
With the enhancement of the "manage images"  perhaps this can be modified a bit to "Browse existing library" to see if we can use existing images?

just a thought

**Comment by Red5ive-UK** [comment]
Seconding this request. Would be great if the 'Set as actor thumbnail' button actually brought up the option to set as thumbnail, alt, avatar or profile rather than just thumbnail.
At the moment the only way to flip between images for the other picture types is to re-upload a image again, even if it's already in the picture library.

**Comment by boi123212321** [comment]
https://github.com/boi123212321/porn-vault/pull/575
