### ISSUE TITLE
[Bug] UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by CMclarty** [boi123212321/porn-vault#522]
Hiya,

I am unfortunately getting an error on install.

**To Reproduce**

- wget latest linux zip into the current working directory, unzip and run `sudo ./porn-vault`
- Changed port to avoid existing service (also tested with standard 3000) in .env file.
- Ubuntu 18.04

Terminal output below:

```
xxxxx@xxxxx:/the/path/releases/linux$ sudo ./porn-vault 
  porn:message Check https://github.com/boi123212321/porn-vault for discussion & updates +0ms
  porn:message Max. memory: 8140 MB +0ms
  porn:message Loading config.yaml... +0ms
  porn:message Registered plugins
  porn:message [] +0ms
  porn:message FFMPEG set to /usr/bin/ffmpeg +0ms
  porn:message FFPROBE set to /usr/bin/ffprobe +0ms
? Enter password [hidden]
  porn:warn Creating backup in backups/k9sqbz45... +0ms
Server running on Port 3333
  porn:success Backup done. +0ms
(node:23755) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (/snapshot/porn-manager/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/porn-manager/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/porn-manager/node_modules/axios/lib/adapters/http.js:236:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:23755) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23755) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.)
```

**Comment by ARandomCat** [comment]
Same happened for me, running `killall izzy && killall twigs` before starting porn-vault fixes it temporarely

**Comment by tcdnghi79** [comment]
I have almost same issued, I am using win 7 64bit, not sure I do some thing wrong or this is a bug, no video scenes add
![image](https://user-images.githubusercontent.com/64823107/81033619-7a990300-8ebe-11ea-9049-a781e948c60c.png)
If i keep video path blank in config no any error but also no video scenes. 
Appreciate for any help or advise.

**Comment by boi123212321** [comment]
@tcdnghi79 looks like your path is not escaped:
Paths with backslashes need escaping:
`E:\\test\\path` instead of `E:\test\path`

**Comment by yur1xpp** [comment]
I have the same issue in Windows 10 when I put `C:/` or `D:/` or `P:/` or any drive letter as the path, here's the error:
![image](https://user-images.githubusercontent.com/34767893/82033619-91660380-96cf-11ea-9993-f58a2a8d6cdf.png)
