### ISSUE TITLE
Does image links show as thumbnails?

### ISSUE THREAD

**Issue by xeleven11** [boi123212321/porn-vault#530]
I only want to self host as a website for myself so that I can scrape images from the web and tag them to organize like your app. I've been trying to find apps that would show thumbnails when the links are posted just like any other ordinary websites but local hosted from my desktop.

**Comment by boi123212321** [comment]
I'm not sure I understand what you're trying to do

**Comment by xeleven11** [comment]
I was talking about sites like ImageFap or Pichunter that have galleries of pornstars and I could save them in an album. However these sites don't support tagging or features such as adding info and I was wondering your app would support this. An offline/local site for myself that I can link external image sources from the web like Imgur so that I don't have to download images in my drive

**Comment by boi123212321** [comment]
Well then no, because it's based around local files
