### ISSUE TITLE
[Bug] No video is playing, only audio

### ISSUE THREAD

**Issue by yur1xpp** [boi123212321/porn-vault#553]
**Describe the bug**
Whenever the video is clicked, only audio is playing, no video. Image #2 show the thumbnail (censored) of the video, and whenever it's clicked, only the audio is playing (as shown in image #1)

**To Reproduce**
1. Go to the scene page, pick on video
2. Click on the thumbnail/video to start playing

**Expected behavior**
A video playing, not just audio.

**Screenshots**
![image](https://user-images.githubusercontent.com/34767893/82035900-c58ef380-96d2-11ea-8612-c021dd26460c.png)

![image](https://user-images.githubusercontent.com/34767893/82037091-44d0f700-96d4-11ea-9a52-29426b639d85.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Firefox and Chrome
 - Version: latest

**Comment by boi123212321** [comment]
https://github.com/boi123212321/porn-vault/wiki/Frequently-Asked-Questions
