### ISSUE TITLE
[Feature] Stays on where it’s left when ‘back’ from clicked video page

### ISSUE THREAD

**Issue by yur1xpp** [boi123212321/porn-vault#554]
**Is your feature request related to a problem? Please describe.**
When you clicked a video on scene page, it takes you to the video page, and when you click ‘<‘ or return to the scene page, the page refreshed and you’ll have to scroll all the way down again to find where you left.

**Describe the solution you'd like**
To stay on the location where I left when clicked back.

**Comment by boi123212321** [comment]
Related to https://github.com/boi123212321/porn-vault/issues/213
