### ISSUE TITLE
[Bug][Feature] .MKV files not supported?

### ISSUE THREAD

**Issue by yur1xpp** [boi123212321/porn-vault#556]
**Describe the bug**
It seems like only .mp4 files is added into the database, .mkv is skipped. Is this a bug or how it supposed to be? Is it possible to add .mkv files support?

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Firefox
 - Version: latest

**Comment by boi123212321** [comment]
https://github.com/boi123212321/porn-vault/wiki/Frequently-Asked-Questions
https://github.com/boi123212321/porn-vault/issues/197
