### ISSUE TITLE
[Feature] For Filesystem path to play the files using default/external player

### ISSUE THREAD

**Issue by yur1xpp** [boi123212321/porn-vault#559]
**Is your feature request related to a problem? Please describe.**
As I understood, some files like avi and flv not supported, it would be great if clicking on the "Filesystem path" link could open up external/default player like VLC or such.

**Describe the solution you'd like**
Click on the path open up external/default player.

**Comment by pizzajohnny** [comment]
There is already an issue for that ( #487 ).
