### ISSUE TITLE
Issue: updating docker looses library

### ISSUE THREAD

**Issue by natcoso9955** [boi123212321/porn-vault#573]
Hi guys, I'm running this in a docker container on unraid. Due to the inability to have db's etc in a /config director or anything. It means that I can't put these files in appdata, and everytime time the container has an update I have to manually copy back all files.

**Comment by boi123212321** [comment]
@leadwolf may know what to do

**Comment by leadwolf** [comment]
I don't understand, you can't mount `/config` to a real non temp folder on your system?

**Comment by natcoso9955** [comment]
I'll need to check the docker structure again, but I think all the dbs are in the root of the docker data folder.

I'll take some screenshots today.

**Comment by natcoso9955** [comment]
Realised that i missed one of the docker config items "LIBRARY_PATH".
