### ISSUE TITLE
[Feature] Video Support for image library

### ISSUE THREAD

**Issue by yoshnopa** [boi123212321/porn-vault#585]
The support for .gif images shows that there is interest in integrating loops into the image library. As the gif format however is very limited in quality, many loops are now saved in normal video files like mp4 or webm (see for example gfycat.com). Therefore, it would be great to have support to scan for videos and play these loops inside the image viewer.
Most widely used here are the mp4 and the webm format, I don't think further support is needed here.

**Comment by boi123212321** [comment]
I don't really think this is feasible.
Internally scenes are what are processed by ffmpeg, "images" are processed by Jimp.
Also there would be no way to really distinguish between scene mp4s and image mp4s, except for the duration maybe, but it doesn't feel right to me
