### ISSUE TITLE
[Feature] Add labels to multiple scenes

### ISSUE THREAD

**Issue by pandalamp** [boi123212321/porn-vault#589]
Would appreciate the option to add -- and possibly remove -- tags/labels to multiple scenes.

Right now (0.22), it seems the only way to apply a label manually is from a scene's page. Since multiple scenes are already able to be selected on the main listing page (with an option to delete them), I'd like to see an option added to apply labels to selected scenes, even if just a simple input box.

Removing tags in bulk would probably require a dedicated UI element to list applicable labels which is probably outside the scope of this simple request. But adding labels and even actors or studios to multiple items should be relatively straightforward and leverage existing assets.

**Comment by boi123212321** [comment]
https://github.com/boi123212321/porn-vault/issues/205
