### ISSUE TITLE
[Bug?] A-Z sort is not case-insensitive

### ISSUE THREAD

**Issue by echo6ix** [boi123212321/porn-vault#590]
**Describe the bug**
Sorting of scenes or performers by alphabetical order is currently case-sensitive.

**To Reproduce**
1. Create the following actors: `Aaa`, `aaa`, `Bbb`
2. Go to the main actors page
3. Sort by `A-Z` in `ascending` order
4. The actors will be sorted in the following order: _Aaa, Bbb, aaa_

**Expected behavior**
Case-insensitive sorting.

Use-case:
- Re: Actors. Not all actor names use the standard naming convention; some go by their usernames from their video hosting sites, eg. `janedoe555`.
- Re: Scenes. Unnamed scenes using their lower or uppercase filenames would be sorted out of order.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - PV Version 0.22.0-rc.1

**Comment by boi123212321** [comment]
should be fixed with https://github.com/boi123212321/gianna/commit/18fe8cd24cf33039833c1005a6ec2c5b53384c15
