### ISSUE TITLE
Question about Plugin "freeones" / Windows 10/ no Picture Download

### ISSUE THREAD

**Issue by Powerbock** [boi123212321/porn-vault#606]
First of all a hearty hello to everybody!
I use the Porn Manager under Windows 10, first of all thanks for this great program.
I have a problem with the plugin "freeones", which I would like to use.
When adding a new actor something doesn't work with the graphic file, it remains empty and I get the following error message:
`
vault:message Running plugin freeones: +0ms
vault:plugin Scraping freeones date for Lisa Ann, dry mode: false... +0ms
vault:plugin No blacklist defined, returning everything... +1ms
vault:plugin Imperial preference not set. Using metric values... +0ms
vault:plugin Getting hair color... +1s
vault:plugin Getting eye color... +2ms
vault:plugin Getting ethnicity... +25ms
vault:plugin Getting height... +1ms
vault:plugin Getting weight... +3ms
vault:plugin Getting birthplace... +1ms
vault:plugin Getting zodiac sign... +3ms
vault:plugin Getting nationality... +1ms
vault:plugin Getting age... +0ms
vault:plugin Getting aliases... +2ms
vault:plugin Getting avatar... +1ms
 vault:message Downloading https://us-img.freeones.com/photos/001/k9/gy/k9gYecmuwqMJeYZQbNGULb/teaser/c9c7d9cb-3b41-479d-be52-fe174387714b.jpg?c=1589746470... +0ms
progress [=======================-----------------] 56% | ETA: 1s | 57/100  vault:error Error while downloading https://us-img.freeones.com/photos/001/k9/gy/k9gYecmuwqMJeYZQbNGULb/teaser/c9c7d9cb-3b41-479d-be52-fe174387714b.jpg?c=1589746470 +0ms
  vault:error {"errno":-4058,"code":"ENOENT","syscall":"open","path":"d:\\porn-manager\\library\\images\\im_kar2jyqf2epCRd8X.jpg?c=1589746470"} +0ms
  vault:error Error: ENOENT: no such file or directory, open 'd:\\porn-manager\\library\\images\\im_kar2jyqf2epCRd8X.jpg?c=1589746470' +0ms
  vault:warn Ran 1 plugins with 1 errors. +0ms`

My config File:
`"PLUGINS": {
  "adultempire_covers": {
   "path": "d:\\porn-manager\\plugins\\adultempire\\main.js"
  },
  "freeones": {
   "path": "d:\\porn-manager\\plugins\\freeones\\main.js"
  }
 },
 "PLUGIN_EVENTS": {
  "actorCreated": [
   "freeones"
  ],
  "sceneCreated": [
   "freeones"
  ],
  "actorCustom": [
   "freeones"
  ],
  "sceneCustom": [
   "freeones"
  ], `

Could someone please be so kind and help me or give me a hint?

System: 
Windows 10 Pro x64
Python 3.8
GIT 

Kind Regards
Powerbock

**Comment by boi123212321** [comment]
I think freeones changed something and that broke the download function
