### ISSUE TITLE
[Feature] Expand the function of Scenes 

### ISSUE THREAD

**Issue by QuinHai** [boi123212321/porn-vault#610]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I have some erotic resources which contains lots of images without video,and I want to manage them as a PACK(Like an erotic manga)

**Describe the solution you'd like**
Maybe expand Scenes function like resources pack,it can contain videos or images or both.And packs can sign with labels.

**Comment by boi123212321** [comment]
https://github.com/boi123212321/porn-vault/issues/30 ?

**Comment by QuinHai** [comment]
NOT ONLY the Image albums.I think it also can contain the videos,voices,texts,etc.That will be more expandability.

**Comment by QuinHai** [comment]
> #30 ?

NOT ONLY the Image albums.I think it also can contain the videos,voices,texts,etc.That will be more expandability.

**Comment by boi123212321** [comment]
I don't think this is really possible, because the scenes just haven't been made with that in mind. It would be a huge rewrite and probably a breaking change.
But image albums will definitely happen
