### ISSUE TITLE
[Bug] Actor scraper not picking up certain names?

### ISSUE THREAD

**Issue by LostRune** [boi123212321/porn-vault#624]
**Describe the bug**
Actor scraper not working with some names? (Like "Sybil")

**To Reproduce**
Name a video and an actress "Sybil". The scraper won't label the scene with "Sybil".
Some names work, some don't. For example there is no problem with "Misha Cross"

**Expected behavior**
The scene should be labelled with the actress "Sybil".

**Screenshots**
https://imgur.com/a/uh4pvRt

**Desktop**
 - OS: [Windows 10]
 - Browser [Opera]
 - Version [0.22.0-rc.2]

**Comment by boi123212321** [comment]
Currently single-named actors are ignored because they tend to cause more havoc than help.
May become an option in the config in the future.
