### ISSUE TITLE
[Feature] Import Filename How to Parse options

### ISSUE THREAD

**Issue by schneckenschnabel** [boi123212321/porn-vault#698]
It would be great to have an option to set how file names should be interpreted.

I currently have my stuff for example named like this:

Studio/2019.05.01 - Actor1, Actor2 - scene title.mp4

Studio works just fine, and it gets found but the imported files still have the name "2019.05.01 - Actor1, Actor2 - scene title"
With no date found.

It would be nice if I could tell porn-vault that "-" is the delimiter and so he knows what each part means:
`<Studio>/<Date> - <Actor(s)> - <Title>`

**Comment by 7yMCat4ix** [comment]
@schneckenschnabel are you by any chance a programmer?

What you describe can be achieved with plugins. To maybe give you a little bit of an idea, I can post the plugin I just wrote for my file structure. It is a little bit different than yours, I have the studio in the actual file name as well. That means, that you probably have to inspect scenePath, sceneName will probably not be enough for you.
```js
module.exports = ctx => {
    var re = /(.+) (\d{2}\.\d{2}\.\d{2}) -([^-]*)(?:- (.*))?/;

    var regexResult = re.exec(ctx.sceneName);
    if (!regexResult){
        return;
    }

    var studio = regexResult[1];
    var date = Date.parse("20" + regexResult[2]);
    var actors = regexResult[3].trim().split(", ");
    if (actors[0] == ""){
        actors = null;
    }
    var name = regexResult[4];

    return {
        name: name,
        description: null,
        releaseDate: date,
        actors: actors,
        labels: null,
        studio: studio
    }
}
```

**Comment by boi123212321** [comment]
@7yMCat4ix 's solution is the way to go. Everyone has their own kind of file naming convention, and some aren't even possible to parse correctly, so it's something that is and will be covered by plugins.
