### ISSUE TITLE
[Bug] Getting an error when trying to run on macOS: porn-vault is damaged and can't be opened

### ISSUE THREAD

**Issue by uemanresu** [boi123212321/porn-vault#704]
**Describe the bug**
When trying to run porn-vault on macOS I get this error: "porn-vault" is damaged and can't be opened. You should move it to the Trash.

**To Reproduce**
1. Unzip
2. In terminal, cd to 'releases > mac' directory
3. In terminal, ./porn-vault

**Expected behavior**
porn-vault should start up, but it doesn't.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Version 0.22.1

**Comment by pnthach95** [comment]
Right-click porn-vault executable file, click Open, then you'll see this dialog:
![image](https://user-images.githubusercontent.com/31266357/89154000-45b94c80-d590-11ea-80a0-0036d9c7ac68.png)
Press Open to grant permission. You may see error, just close that terminal.
Run `./porn-vault` in new terminal and porn-vault should start up.

**Comment by uemanresu** [comment]
> This is not a bug. This is MacOS security protocol.
> Right-click porn-vault executable file, click Open, then you'll see this dialog:
> ![image](https://user-images.githubusercontent.com/31266357/89154000-45b94c80-d590-11ea-80a0-0036d9c7ac68.png)
> Press Open to grant permission. You may see error, just close that terminal.
> Run `./porn-vault` in new terminal and porn-vault should start up.

This doesn't work. I get the same error "porn-vault" is damaged and can't be opened. You should move it to the Trash." even when right clicking and clicking open. I don't see that dialog asking to grant permissions - and never have seen it with porn-vault. 

![Screen Shot 2020-08-07 at 11 20 49 AM](https://user-images.githubusercontent.com/68611068/89676369-6808de00-d8a0-11ea-930b-9742e21237c4.png)

**Comment by pnthach95** [comment]
I forgot that you should turn off [Gatekeeper](https://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/) and [SIP](https://www.macworld.co.uk/how-to/mac/how-turn-off-mac-os-x-system-integrity-protection-rootless-3638975/) first.
