### ISSUE TITLE
[Feature] Automatic tagging based on identifier in filename

### ISSUE THREAD

**Issue by ttrv65ebyng** [boi123212321/porn-vault#706]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
When a video is downloaded from certain sources using youtube-dl, it sometimes contains the identifier of the video and site in the name (such as "{NAME OF VIDEO} - ph#########.mp4"). Would it be possible for porn-vault to fetch tags from the source site based off these ids and add them to the video in our library automatically when a video is added, or as a script run periodically on the library's new files?

**Additional context**
On closer inspection, Pornhub, for example, contains all the tags in the HTML under the div classes .categoriesWrapper and .tagsWrapper when checking https://www.pornhub.com/view_video.php?viewkey=ph#########, though I din't know if this is as helpful as an API, since one would have to parse html. There are a few unofficial APIs, and [this](https://github.com/Derfirm/pornhub-api) one on github seems to have a function to get all tags/categories from a video.

**Comment by boi123212321** [comment]
Use/write a plugin
