### ISSUE TITLE
[Bug] sorting by number of scenes not updated when scanning

### ISSUE THREAD

**Issue by 7yMCat4ix** [boi123212321/porn-vault#780]
**Describe the bug**
After scanning scenes, the number of scenes sort order does not seem to get updated. Actors (and presumably studios) remain in the order they were before scanning, despite their card showing the updated number of scenes.
The only fix at the moment is to restart the whole app. Then the order is updated.

**To Reproduce**
1. Scan enough scenes of a specific actor for them to overtake another actor in number of scenes.
2. Look at actor page with number of scenes sort order.
3. Actor order should be as if the scanning never happened, despite their card showing the new numbers.

**Expected behavior**
I would expect the sort order to be updated when scanning.

**Screenshots**
After scanning, before restarting app:
![wrong_order](https://user-images.githubusercontent.com/68701012/92230713-e2cb1600-eeab-11ea-9b4b-4851b07b67be.png)

after restarting app:
![correct_order](https://user-images.githubusercontent.com/68701012/92230783-f70f1300-eeab-11ea-8375-081794179d35.png)

**Comment by boi123212321** [comment]
The actor cards show an up to date, freshly calculated value
While the sort direction is controlled by how it's indexed.

When a scene is attached to an actor, that actor needs to be indexed
